"""
Django settings for myproject.

Generated by 'django-admin startproject' using Django 4.x.
"""

import os
from pathlib import Path



# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'your-secret-key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
USE_TZ = False


# ============================================
# APPLICATION DEFINITION
# ============================================

INSTALLED_APPS = [
    'jazzmin',  # 🌿 Jazzmin admin theme
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',  # your custom app
]

# ============================================
# JAZZMIN SETTINGS
# ============================================

JAZZMIN_SETTINGS = {
    "site_title": "EcoBayanihan Admin",
    "site_header": "EcoBayanihan Dashboard",
    "welcome_sign": "Welcome to EcoBayanihan Admin 🌿",
    "site_brand": "EcoBayanihan",
    "site_logo": "images/ecologo.png",  # path from your static folder
    "site_logo_classes": "img-circle elevation-3",
    "copyright": "EcoBayanihan Team",
    "show_ui_builder": True,

    # 🎨 Custom color palette and style
    "theme": "default",
    "dark_mode_theme": "darkly",
    "navigation_expanded": True,

    "topmenu_links": [
        {"name": "Home", "url": "/", "permissions": ["auth.view_user"]},
        {"app": "auth"},
    ],

    "show_sidebar": True,
    "navigation_depth": 3,
    "icons": {
        "auth": "fas fa-users-cog",
        "myapp.Event": "fas fa-leaf",
        "myapp.Volunteer": "fas fa-user",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-success navbar-dark",   # green navbar
    "sidebar": "sidebar-dark-success",        # green sidebar
    "theme": "default",
    "brand_colour": "navbar-success",
    "accent": "accent-success",
    "no_navbar_border": True,
    "navbar_small_text": False,
    "body_small_text": False,
}

# ============================================
# MIDDLEWARE
# ============================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============================================
# URLS, TEMPLATES, WSGI
# ============================================

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'myapp', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# ============================================
# DATABASE
# ============================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ============================================
# PASSWORD VALIDATION
# ============================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ============================================
# INTERNATIONALIZATION
# ============================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# ============================================
# STATIC FILES
# ============================================

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ============================================
# DEFAULT AUTO FIELD
# ============================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
