# Generated by Django 5.2.5 on 2025-10-16 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('place', models.CharField(choices=[('beach', 'Beach'), ('park', 'Park'), ('street', 'Street'), ('river', 'River'), ('general', 'General Cleanup')], max_length=20)),
                ('specific_location', models.CharField(help_text='Specific address or location details', max_length=300)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.IntegerField(help_text='Duration in hours')),
                ('points', models.IntegerField(default=10, help_text='Points volunteers will earn')),
                ('max_participants', models.IntegerField(default=20, help_text='Maximum number of volunteers')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanup_type', models.CharField(choices=[('beach', 'Beach'), ('park', 'Park'), ('street', 'Street'), ('river', 'River'), ('general', 'General Cleanup')], default='general', max_length=20)),
                ('points_earned', models.IntegerField(default=10)),
                ('date_participated', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.cleanupevent')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.participant')),
            ],
        ),
        migrations.CreateModel(
            name='CleanupRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('points_awarded', models.BooleanField(default=False)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('proof_notes', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_registrations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cleanupevent')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.participant')),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('participant', 'event')},
            },
        ),
    ]
