# Generated by Django 5.2.5 on 2025-10-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleanupevent',
            old_name='title',
            new_name='name',
        ),
    ]
