# Generated by Django 5.2.5 on 2025-11-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_title_cleanupevent_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AlterField(
            model_name='cleanupevent',
            name='max_participants',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='cleanupevent',
            name='points',
            field=models.IntegerField(default=10),
        ),
    ]
